name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # GitHub Secrets の名前と一致させています
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          ###### プロジェクト構成に合わせて修正が必要な箇所 ######
          # App のソースコードがあるディレクトリ
          app_location: "frontend" 
          
          # API (Azure Functions 等) のソースコードがあるディレクトリ
          # Next.js の場合は空文字列にする必要があります
          api_location: "" 
          
          # ビルド後の静的ファイルが出力されるディレクトリ
          # Next.js の場合は ".next" になります
          output_location: ".next" 
          ################################################
        env:
          # NestJS バックエンドの Azure App Service URL
          API_URL: ${{ secrets.AZURE_BACKEND_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"